<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Оформление заказа</title>
    <link rel="stylesheet" href="css/css.css">
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            background: rgb(99, 25, 141);
        }
    </style>
</head>
<body>
    <div>
        <h1>Оформление заказа</h1>
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img id="shopImage" src="images/rocket-shop-banner.10242b36569edc3db2545da7c1cac150.jpg" usemap="#image-map">

        <map name="image-map">
            <area class="area1" onclick="changeColor('area1')" coords="641,60,648,139,702,210,930,199,994,114,993,16" shape="poly">
            <area class="area2" href="https://rocketshop.nl/" coords="642,429,643,451,664,486,773,406,754,389,689,393,671,428" shape="poly">
            <area class="area3" onclick="resizeImage('area3')" coords="631,351,634,366,695,351,686,329,665,324,651,349" shape="poly">
            <area class="area4" href="images/scale_1200.png" coords="334,2,332,18,329,52,348,76,379,64,372,20,360,5" shape="poly">
            <area class="area5" onclick="changeBackgroundColor('area5')" coords="634,434,619,434,610,444,622,454,610,473,638,473,642,493,659,481" shape="poly">
        </map>
    </div>
    <form action="./scripts/data.php" method="post" id="order-form">
        <label for="first-name">Имя:</label>
        <input type="text" id="first-name" name="first-name" required>
        
        <label for="last-name">Фамилия:</label>
        <input type="text" id="last-name" name="last-name" required>
        
        <label for="middle-name">Отчество:</label>
        <input type="text" id="middle-name" name="middle-name">
        
        <label for="address">Адрес доставки:</label>
        <input type="text" id="address" name="address" required>
        
        <label for="phone">Телефон:</label>
        <input type="tel" id="phone" name="phone" required>
        
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        
        <label for="products">Выберите товар:</label>
        <select id="products" name="products" required>
            <option value="product1">RTX 3080 ti</option>
            <option value="product2">Nike dunk low travis scott</option>
            <option value="product3">Холодильник</option>
        </select>
        
        <label for="comments">Комментарий к заказу:</label>
        <textarea id="comments" name="comments" rows="4"></textarea>
        
        <div class="submit-button-container">
            <button class="submit-button" type="submit">Отправить заказ</button>
        </div>
    </form>
    <script>
        function changeColor(area) {
            alert('Вы кликнули на область Rocket Shop');
        }
        function resizeImage(area) {
            var shopImage = document.getElementById('shopImage');
            shopImage.style.width = '70%';
            shopImage.style.height = 'auto'; 
        }
        function changeBackgroundColor(area) {
            document.body.style.backgroundColor = '#000';
        }
    </script>
</body>
</html>
